name: Pull requests - Verifiacion

on: 
    pull_request:
        branches:
            - main
env:
    DOTNET_VERSION: '10.0.103'
    BUILD_CONFIGURATION: 'Release'

jobs:
    build:
        name: "Job pull request verificacion"
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v2

            - name: Setup .NET
              uses: actions/setup-dotnet@v1
              with:
                  dotnet-version: ${{ env.DOTNET_VERSION }}

            - name: Build with dotnet
              run: dotnet build --configuration ${{ env.BUILD_CONFIGURATION }}
             
            - name: Format with dotnet
              run: dotnet format  

            - name: Test with dotnet
              run: dotnet test --configuration ${{ env.BUILD_CONFIGURATION }}